services:
  my-server:
    build: .
    ports:
      - 3000:3000
    depends_on:
      - my-db
    environment:
      - DB_HOST=my-db
      - DB_PORT=5432
      - DB_USER=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_DATABASE}
    volumes:
      - .:/app
    working_dir: /app
    entrypoint: ['./wait-for-it.sh', 'my-db:5432', '--', 'npm', 'run', 'start']
    # 컨테이너가 시작되면:
    # 1. wait-for-it.sh를 실행해 my-db:5432가 열릴 때까지 대기
    # 2. 대기 후 npm run start 명령어로 NestJS 서버를 실행
  my-db:
    image: postgres:15
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - ./postgresql_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD', 'pg_isready', '-U', 'postgres']
      interval: 10s
      timeout: 5s
      retries: 5
